#!/bin/bash 

#PBS -N OPENMP
#PBS -o OUT
#PBS -q hpc-course
#PBS -l nodes=1:ppn=4,walltime=00:10:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk.exe input_128x128.params obstacles_128x128_box.dat"

#! Run options for the application
options=""
