#!/bin/bash 

#PBS -N OPENMP
#PBS -o OUT

#PBS -l nodes=1:ppn=16,walltime=00:10:00

#! submit to the 'hpc-course' queue
#PBS -q hpc-course

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk.exe input_128x256.params obstacles_128x256_sandwich.dat"

#! Run options for the application
options=""

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

#! Run the simple serial job 
$application $options
